spring.application.name=SpeechHelper
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_User}
spring.datasource.password=${DB_Password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

jwt.secret=${Jwt_security}
jwt.expiration = 3600000
jwt.refresh-expiration=1209600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pjsleey12312@gmail.com
spring.mail.password=${Google_Password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

gemini.api.key=${AI_Key}